### ISSUE TITLE
Community poker (hold 'em)

### ISSUE THREAD

**Issue by bleakley** [brunoscopelliti/poker-rank#1]
I would be nice if this library could accept a hand with more than five cards (such as seven), and then find the best five card hand out of the seven. This would let the library be used for texas hold 'em games.

**Comment by brunoscopelliti** [comment]
You can use https://github.com/brunoscopelliti/poker-combinations to get all the possible combinations of seven cards, and then https://github.com/brunoscopelliti/poker-rank to determine the best one.
Eg.

```
const getCombinations = require("poker-combinations");
const sortByRank = require("poker-rank");
const combinations = getCombinations([{card: "2", type: "C"}, ... /* seven cards */ ]);
const [bestHand] = sortByRank(combinations);
```

I'm not going to extend https://github.com/brunoscopelliti/poker-rank to support this use case.
